In [5]:
import warnings
warnings.filterwarnings("ignore")
import logging
logging.basicConfig(level=logging.ERROR)
data_dir='D:\\_NILESH\\dissertation\\data\\'

In [6]:
# import requests
# from tqdm import tqdm
# import pandas as pd

# # List of URLs
# urls = [
#     # '',# 1993
#     # '',# 1994
#     # '',# 1995
#     # '',# 1996
#     # '',# 1997
#     # '',# 1998
#     # '',# 1999
#     'https://omniweb.gsfc.nasa.gov/staging/omni_min_def_8aIlYUTj9B.lst',#2000
#     "https://omniweb.gsfc.nasa.gov/staging/omni_min_def_h7EHhwvge1.lst",#2001
#     "https://omniweb.gsfc.nasa.gov/staging/omni_min_def_6YsumxMmxd.lst",#2002
#     "https://omniweb.gsfc.nasa.gov/staging/omni_min_def_oJqd3J6VE8.lst",#2003
#     'https://omniweb.gsfc.nasa.gov/staging/omni_min_def_DOQVsQ60kd.lst',#2004
#     'https://omniweb.gsfc.nasa.gov/staging/omni_min_def_Fo0Mf9yauj.lst',#2005
#     'https://omniweb.gsfc.nasa.gov/staging/omni_min_def_ncnDM3PxSD.lst',#2006
#     'https://omniweb.gsfc.nasa.gov/staging/omni_min_def_LdPwrXYqvY.lst',#2007
#     'https://omniweb.gsfc.nasa.gov/staging/omni_min_def_lV0AYb27Rc.lst',#2008
#     'https://omniweb.gsfc.nasa.gov/staging/omni_min_def_mQYAVwfste.lst',#2009
#     'https://omniweb.gsfc.nasa.gov/staging/omni_min_def_gtkR5UxaNA.lst',#2010
#     'https://omniweb.gsfc.nasa.gov/staging/omni_min_def_iPncQMvmx3.lst',#2011
#     'https://omniweb.gsfc.nasa.gov/staging/omni_min_def_1k5Wocz1oT.lst',#2012
#     'https://omniweb.gsfc.nasa.gov/staging/omni_min_def_wQYjwgN2RQ.lst',#2013
#     'https://omniweb.gsfc.nasa.gov/staging/omni_min_def_hT1N5RH2xz.lst',#2014
#     'https://omniweb.gsfc.nasa.gov/staging/omni_min_def_jLmeOjgrxw.lst',#2015
#     'https://omniweb.gsfc.nasa.gov/staging/omni_min_def_Dgtq5TuWgX.lst',#2016
#     'https://omniweb.gsfc.nasa.gov/staging/omni_min_def_iuQfKvD8E_.lst',#2017
#     'https://omniweb.gsfc.nasa.gov/staging/omni_min_def_8wbuoWutH1.lst',#2018
#     'https://omniweb.gsfc.nasa.gov/staging/omni_min_def_3NP8P5TMj2.lst',#2019
#     'https://omniweb.gsfc.nasa.gov/staging/omni_min_def_cUs95pD2CH.lst',#2020
#     'https://omniweb.gsfc.nasa.gov/staging/omni_min_def_Fx43KAFXE6.lst',#2021
#     'https://omniweb.gsfc.nasa.gov/staging/omni_min_def_RzIZ60i31N.lst',#2022
#     'https://omniweb.gsfc.nasa.gov/staging/omni_min_def_qvjYa7tZjr.lst',#2023
# ]

# # Define the directory where data will be saved
# data_dir = 'D:\\_NILESH\\dissertation\\data\\'

# # Column names
# columns = [
#     "Year", "Month", "Day", "Hour",
#     "Field magnitude average, nT", "RMS SD B scalar, nT",
#     "Speed, km/s", "Proton Density, n/cc",
#     "Proton Temperature, K", "Flow pressure, nPa",
#     "Electric field, mV/m"
# ]

# # Create a DataFrame to hold the data
# data_df = pd.DataFrame(columns=columns)

# # Iterate through the URLs
# for url in tqdm(urls):
#     # Send the GET request
#     response = requests.get(url)
#     # Get the content of the page
#     content = response.text.split("\n")

#     # Iterate through the lines of the content and parse the data
#     for line in content:
#         # Split the line by whitespace
#         values = line.split()
#         # Skip the lines with insufficient values
#         if len(values) < 11:
#             continue
#         # Convert the values into appropriate types
#         values = [int(values[0]), int(values[1]), int(values[2]), int(values[3])] + [float(v) for v in values[4:]]
#         # Append the data to the DataFrame
#         data_df.loc[len(data_df)] = values

# # Save the DataFrame to a CSV file
# data_df.to_csv(data_dir + 'omni_data.csv', index=False)

In [7]:
# import os
# import pandas as pd
# from tqdm import tqdm

# # Directory containing the .lst files
# dir = 'D:\\_NILESH\\dissertation\\data\\raw\\wind'

# # Output directory for the CSV file
# data_dir = 'D:\\_NILESH\\dissertation\\data\\'

# # Column names according to the specified format
# columns = [
#     "Year", "Day", "Hour", "Minute",
#     "Field magnitude average, nT", "RMS SD B scalar, nT",
#     "Speed, km/s", "Proton Density, n/cc",
#     "Proton Temperature, K", "Flow pressure, nPa",
#     "Electric field, mV/m"
# ]

# # Create an empty DataFrame to hold the data
# data_df = pd.DataFrame(columns=columns)

# # Get the list of .lst files
# lst_files = [filename for filename in os.listdir(dir) if filename.endswith(".lst")]

# # Iterate through the files in the directory with a progress bar
# for filename in tqdm(lst_files, desc='Processing files', unit='file'):
#     filepath = os.path.join(dir, filename)
#     with open(filepath, 'r') as file:
#         # Read each line from the file
#         for line in file:
#             # Split the line by whitespace and convert the values to the appropriate types
#             values = line.split()
#             if len(values) < 11:
#                 continue
#             values = [int(values[0]), int(values[1]), int(values[2]), int(values[3])] + [float(v) for v in values[4:]]
#             # Append the data to the DataFrame
#             data_df.loc[len(data_df)] = values

# # Save the DataFrame to a CSV file in the specified data directory
# data_df.to_csv(os.path.join(data_dir, 'solar_wind.csv'), index=False)

In [15]:
import os
import pandas as pd
from tqdm import tqdm

# Directory containing the .lst files
wind_raw_dir = 'D:\\_NILESH\\dissertation\\data\\raw\\wind\\'
wind_temp='D:\\_NILESH\\dissertation\\data\\raw\\wind_temp\\'

# Output directory for the CSV files
data_dir = 'D:\\_NILESH\\dissertation\\data\\'

# Column names according to the specified format
columns = [
    "Year", "Day", "Hour", "Minute",
    "Field magnitude average, nT", "RMS SD B scalar, nT",
    "Speed, km/s", "Proton Density, n/cc",
    "Proton Temperature, K", "Flow pressure, nPa",
    "Electric field, mV/m"
]

# Get the list of .lst files
lst_files = [filename for filename in os.listdir(wind_raw_dir) if filename.endswith(".lst")]

# Iterate through the files in the directory with a progress bar
for filename in tqdm(lst_files, desc='Processing files', unit='file'):
    filepath = os.path.join(wind_raw_dir, filename)
    
    # Create a list to hold the rows
    data_rows = []

    with open(filepath, 'r') as file:
        # Read each line from the file
        for line in file:
            # Split the line by whitespace and convert the values to the appropriate types
            values = line.split()
            if len(values) < 11:
                continue
            values = [int(values[0]), int(values[1]), int(values[2]), int(values[3])] + [float(v) for v in values[4:]]
            data_rows.append(values)

    # Create a DataFrame from the rows
    data_df = pd.DataFrame(data_rows, columns=columns)

    # Save the DataFrame to a CSV file in the specified data directory, using the same name as the original .lst file
    csv_filename = filename.replace('.lst', '.csv')
    data_df.to_csv(os.path.join(wind_temp, csv_filename), index=False)

Processing files: 100%|██████████| 24/24 [01:37<00:00,  4.07s/file]

In [16]:
# Output file for the combined CSV
output_file = 'D:\\_NILESH\\dissertation\\data\\solar_wind.csv'

# Get the list of CSV files
csv_files = [filename for filename in os.listdir(wind_temp) if filename.endswith(".csv")]

# Initialize an empty DataFrame to hold the combined data
combined_data_df = pd.DataFrame()

# Iterate through the CSV files in the directory with a progress bar
for filename in tqdm(csv_files, desc='Combining files', unit='file'):
    filepath = os.path.join(wind_temp, filename)
    # Read the CSV file into a DataFrame
    data_df = pd.read_csv(filepath)
    # Append the DataFrame to the combined data
    combined_data_df = combined_data_df.append(data_df, ignore_index=True)

# Save the combined DataFrame to the output CSV file
combined_data_df.to_csv(output_file, index=False)

print(f"All CSV files have been combined into {output_file}")

Combining files: 100%|██████████| 24/24 [00:07<00:00,  3.01file/s]

All CSV files have been combined into D:\_NILESH\dissertation\data\solar_wind.csv

In [18]:
windy_df=pd.read_csv(data_dir+'solar_wind.csv')
windy_df.value_counts().unique

<bound method Series.unique of Year  Day  Hour  Minute  Field magnitude average, nT  RMS SD B scalar, nT  Speed, km/s  Proton Density, n/cc  Proton Temperature, K  Flow pressure, nPa  Electric field, mV/m
2000  1    0     0       6.82                         0.20                 99999.9      999.99                9999999.0              99.99                999.99                 1
2015  18   11    6       5.38                         0.07                 329.5        6.01                  30489.0                1.31                -0.16                   1
                 14      5.38                         0.03                 344.3        6.19                  30356.0                1.47                 0.61                   1
                 13      5.27                         0.03                 342.1        5.63                  19520.0                1.32                 0.69                   1
                 12      5.39                         0.09                 339.4        6.40                  27775.0                1.47                 0.76                   1
                                                                                                                                                                                ..
2005  18   1     28      12.77                        0.29                 580.8        22.69                 129134.0               15.31               -0.88                   1
                 27      13.51                        0.13                 574.1        23.31                 151381.0               15.37               -0.16                   1
                 26      13.96                        1.42                 563.2        18.89                 140902.0               11.98                3.19                   1
                 25      14.70                        1.23                 552.1        13.98                 126907.0               8.52                 5.21                   1
2023  178  0     50      5.50                         0.02                 99999.9      999.99                9999999.0              99.99                999.99                 1
Length: 5613352, dtype: int64>

In [19]:
windy_df

,Year,Day,Hour,Minute,"Field magnitude average, nT","RMS SD B scalar, nT","Speed, km/s","Proton Density, n/cc","Proton Temperature, K","Flow pressure, nPa","Electric field, mV/m"
0,2000,1,0,0,6.82,0.20,99999.9,999.99,9999999.0,99.99,999.99
1,2000,1,0,1,6.99,0.16,664.7,3.12,343841.0,2.76,-0.72
2,2000,1,0,2,6.99,0.20,663.2,3.24,326583.0,2.85,-1.49
3,2000,1,0,3,6.83,0.00,662.2,3.11,306470.0,2.73,-1.84
4,2000,1,0,5,6.98,0.00,688.4,2.55,355046.0,2.42,-3.26
...,...,...,...,...,...,...,...,...,...,...,...
5613347,2023,178,0,46,5.46,0.01,497.9,1.84,109793.0,0.91,1.03
5613348,2023,178,0,47,5.45,0.00,99999.9,999.99,9999999.0,99.99,999.99
5613349,2023,178,0,48,5.49,0.00,99999.9,999.99,9999999.0,99.99,999.99
5613350,2023,178,0,49,5.44,0.00,99999.9,999.99,9999999.0,99.99,999.99
5613351,2023,178,0,50,5.50,0.02,99999.9,999.99,9999999.0,99.99,999.99